name: Delete old artifacts
on:
  schedule:
    - cron: '20 17 * * *'

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      #- uses: kolpav/purge-artifacts-action@v1
      - uses: c-hive/gha-remove-artifacts@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          age: '8 days'
          #expire-in: 8days
