name: Delete old artifacts runs
on:
  schedule:
    - cron: '45 8 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Delete old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '8 day'
